#### 包管理

In [4]:
# 包管理
from numpy import *
import math
arr = arange(12).reshape(4,3)
arr.shape
arr
pai = math.pi
pai
math.floor(pai)
int(pai)
math.acos(0.2)
math.cos(0.1)
math.sqrt(3)

(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

3.141592653589793

3

3

1.3694384060045657

0.9950041652780257

1.7320508075688772

#### 变量管理

In [6]:
# 多赋值

p = (4, 5)
x, y = p
x
y

data = ['string', 1, 2.0, 30000000000000, (1, 2, 3), {'name': 'haijian', 'age': 38}, [2.0, 3.0, 4.], 'string2']
elm1, elm2, elm3, elm4, elm5, elm6, elm7, _ = data
elm1, type(elm1)
elm2, type(elm2)
elm3, type(elm3)
elm4, type(elm4)
elm5, type(elm5)
elm6, type(elm6)
elm7, type(elm7)

my_str1 = "我是曾海剑"

c1, c2, c3, c4, c5 = my_str1
c1
c2
c3
c4
c5

# 变量
my_str2 = """<html>
""i'am haijian"
asdfasdfasd
</html>"""

my_str2

arr1 = ["string", 1, 1.0, 2000]
arr1[0]
arr1[1]
arr1[1:-1]

d = {'name': 'haijian', 'age': 37}
d['name']
d['age']



4

5

('string', str)

(1, int)

(2.0, float)

(30000000000000, int)

((1, 2, 3), tuple)

({'age': 38, 'name': 'haijian'}, dict)

([2.0, 3.0, 4.0], list)

'我'

'是'

'曾'

'海'

'剑'

'<html>\n""i\'am haijian"\nasdfasdfasd\n</html>'

'string'

1

[1, 1.0]

'haijian'

37

In [26]:
# 不定长参数

record = ('Dave', 'dave@example.com', '773-555-1212', '847-555-1212')
name, email, *phone_numbers = record
name
email
phone_numbers

*trailing, current = [10, 8, 7, 1, 9, 5, 10, 3]
trailing, current

def drop_first_last(*grades):
    first, *middle, last = grades
    return (middle)

drop_first_last(1, 2, 3, 4, 5)

records = [
    ('foo', 1, 2),
    ('bar', 'hello'),
    ('foo', 3, 4),
]

def do_foo(x, y):
    print('foo', x, y)

def do_bar(s):
    print('bar', s)

for tag, *args in records:
    if tag == 'foo':
        do_foo(*args)
    elif tag == 'bar':
        do_bar(*args)
        
line = 'nobody:*:-2:-2:Unprivileged User:/var/empty:/usr/bin/false'
uname, *_, homedir, sh = line.split(':')
uname, homedir, sh

def sum(items):
    head, *tail = items
    return head + sum(tail) if tail else head

sum([1,2,3,4,5,6,7,8,9,10])

'Dave'

'dave@example.com'

['773-555-1212', '847-555-1212']

([10, 8, 7, 1, 9, 5, 10], 3)

[2, 3, 4]

foo 1 2
bar hello
foo 3 4


('nobody', '/var/empty', '/usr/bin/false')

55

In [41]:
# 保留最后 N 个元素

# deque是固定长度队列，当append新元素的时候，如果已经到达maxlen，那么会把最早的元素挤出队列
import collections

q1 = collections.deque(maxlen=3)
q1.append(1)
q1.append(2)
q1.append(3)
q1.append(4)

q1

q2 = collections.deque()
q2.append(1)
q2.append(2)
q2.append(3)
q2.appendleft(4)

q2.insert(-1, 5)
q2


deque([2, 3, 4])

deque([4, 1, 2, 5, 3])

In [75]:
import numpy as np
import heapq

arr1 = np.random.normal(size=[10])
arr1.sort(axis=0)
arr1
arr1[:3]

heapq.nlargest(5, arr1)
heapq.nsmallest(5, arr1)

portfolio = [
    {'name': 'IBM', 'shares': 100, 'price': 91.1},
    {'name': 'AAPL', 'shares': 50, 'price': 543.22},
    {'name': 'FB', 'shares': 200, 'price': 21.09},
    {'name': 'HPQ', 'shares': 35, 'price': 31.75},
    {'name': 'YHOO', 'shares': 45, 'price': 16.35},
    {'name': 'ACME', 'shares': 75, 'price': 115.65}
]
cheap = heapq.nsmallest(3, portfolio, key=lambda s: s['price'])
expensive = heapq.nlargest(3, portfolio, key=lambda s: s['price'])

"cheap", cheap
"expensive", expensive

portfolio.sort(key=lambda i: i['shares'], reverse=True)
"portfolio:", portfolio

array([-1.57510517, -1.07000422, -0.46497176, -0.28413993, -0.0105018 ,
        0.5970966 ,  0.97685338,  1.10478463,  1.1253005 ,  2.01111201])

array([-1.57510517, -1.07000422, -0.46497176])

[2.0111120076370734,
 1.1253005013327722,
 1.104784630413755,
 0.97685337568408837,
 0.59709659855067954]

[-1.5751051653340236,
 -1.0700042216988876,
 -0.46497176343281632,
 -0.28413992934110582,
 -0.010501801176449848]

('cheap',
 [{'name': 'YHOO', 'price': 16.35, 'shares': 45},
  {'name': 'FB', 'price': 21.09, 'shares': 200},
  {'name': 'HPQ', 'price': 31.75, 'shares': 35}])

('expensive',
 [{'name': 'AAPL', 'price': 543.22, 'shares': 50},
  {'name': 'ACME', 'price': 115.65, 'shares': 75},
  {'name': 'IBM', 'price': 91.1, 'shares': 100}])

('portfolio:',
 [{'name': 'FB', 'price': 21.09, 'shares': 200},
  {'name': 'IBM', 'price': 91.1, 'shares': 100},
  {'name': 'ACME', 'price': 115.65, 'shares': 75},
  {'name': 'AAPL', 'price': 543.22, 'shares': 50},
  {'name': 'YHOO', 'price': 16.35, 'shares': 45},
  {'name': 'HPQ', 'price': 31.75, 'shares': 35}])

In [5]:
import collections
d = collections.defaultdict(list)
pairs = [('a', 1), ("a", 2), ("b", 3.2)]
for key, value in pairs:
    d[key].append(value)

d['d'] = 3
d['e'] = {"k": "v"}
d['c'] = "3"  
d

list(d)

import json
json.dumps(d)

json.dumps({"k1": [ {"kk": "vv"}, {"kk": "vv2"}]})

prices = {
    'ACME': 45.23,
    'AAPL': 612.78,
    'IBM': 205.55,
    'HPQ': 37.20,
    'FB': 10.75
}
min_price = min(zip(prices.values(), prices.keys()))
max_price = max(zip(prices.values(), prices.keys()))
min_price
max_price

sorted(zip(prices.values(), prices.keys()),reverse=True)

d1 = {"a", "b", "c"}
d2 = {"c", "d"}
d1 - d2
d1 & d2
prices.keys() 
prices.values()
type(prices.keys())

defaultdict(list, {'a': [1, 2], 'b': [3.2], 'c': '3', 'd': 3, 'e': {'k': 'v'}})

['a', 'b', 'd', 'e', 'c']

'{"a": [1, 2], "b": [3.2], "d": 3, "e": {"k": "v"}, "c": "3"}'

'{"k1": [{"kk": "vv"}, {"kk": "vv2"}]}'

(10.75, 'FB')

(612.78, 'AAPL')

[(612.78, 'AAPL'),
 (205.55, 'IBM'),
 (45.23, 'ACME'),
 (37.2, 'HPQ'),
 (10.75, 'FB')]

{'a', 'b'}

{'c'}

dict_keys(['ACME', 'AAPL', 'IBM', 'HPQ', 'FB'])

dict_values([45.23, 612.78, 205.55, 37.2, 10.75])

dict_keys

In [34]:
# 消除重复元素

arr1 = [1, 3, 2, 5, 3, 4]
type(arr1)
set(arr1)

list(arr1)

arr2 = {1, 2, 3, 3, 4}
arr2
type(arr2)

type([1,2,3])
type({1,2,3})
type({"name": "haijian", "age":38})
type((1, 2))
type(1)

set1 = {1,3,2}
for s in set1:
    print(s)
    
def add(x,y):
    return x+y

# 切片
print("####")
s = slice(1,6,2)    
arr = range(10)
for i in arr[s]:
    print(i)
s.indices(1)    
s.start
s.stop
s.step


list

{1, 2, 3, 4, 5}

[1, 3, 2, 5, 3, 4]

{1, 2, 3, 4}

set

list

set

dict

tuple

int

1
2
3
####
1
3
5


(1, 1, 2)

1

6

2

In [1]:
words = [
    'look', 'into', 'my', 'eyes', 'look', 'into', 'my', 'eyes',
    'the', 'eyes', 'the', 'eyes', 'the', 'eyes', 'not', 'around', 'the',
    'eyes', "don't", 'look', 'around', 'the', 'eyes', 'look', 'into',
    'my', 'eyes', "you're", 'under'
]
from collections import Counter
word_counts = Counter(words)
# 出现频率最高的3个单词
top_three = word_counts.most_common(3)
print(top_three)
word_counts.values()
word_counts.keys()


[('eyes', 8), ('the', 5), ('look', 4)]


dict_values([4, 3, 3, 8, 5, 1, 2, 1, 1, 1])

dict_keys(['look', 'into', 'my', 'eyes', 'the', 'not', 'around', "don't", "you're", 'under'])

In [9]:
rows = [
    {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003},
    {'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
    {'fname': 'John', 'lname': 'Cleese', 'uid': 1001},
    {'fname': 'Big', 'lname': 'Jones', 'uid': 1004}
]
# 根据任意的字典字段来排序输入结果行是很容易实现的，代码示例：

from operator import itemgetter
rows_by_fname = sorted(rows, key=itemgetter('fname'))
rows_by_uid = sorted(rows, key=itemgetter('uid'))
rows_by_fname
rows_by_uid
sorted(rows, key=lambda r: (r['lname'], r['fname']))
sorted(rows, key=lambda r: r['uid'])



rows = [
    {'address': '5412 N CLARK', 'date': '07/01/2012'},
    {'address': '5148 N CLARK', 'date': '07/04/2012'},
    {'address': '5800 E 58TH', 'date': '07/02/2012'},
    {'address': '2122 N CLARK', 'date': '07/03/2012'},
    {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'},
    {'address': '1060 W ADDISON', 'date': '07/02/2012'},
    {'address': '4801 N BROADWAY', 'date': '07/01/2012'},
    {'address': '1039 W GRANVILLE', 'date': '07/04/2012'},
]
from operator import itemgetter
from itertools import groupby

# Sort by the desired field first
rows.sort(key=itemgetter('date'))
# Iterate in groups
for date, items in groupby(rows, key=itemgetter('date')):
    print(date)
    for i in items:
        print(' ', i)

[{'fname': 'Big', 'lname': 'Jones', 'uid': 1004},
 {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003},
 {'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
 {'fname': 'John', 'lname': 'Cleese', 'uid': 1001}]

[{'fname': 'John', 'lname': 'Cleese', 'uid': 1001},
 {'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
 {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003},
 {'fname': 'Big', 'lname': 'Jones', 'uid': 1004}]

[{'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
 {'fname': 'John', 'lname': 'Cleese', 'uid': 1001},
 {'fname': 'Big', 'lname': 'Jones', 'uid': 1004},
 {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003}]

[{'fname': 'John', 'lname': 'Cleese', 'uid': 1001},
 {'fname': 'David', 'lname': 'Beazley', 'uid': 1002},
 {'fname': 'Brian', 'lname': 'Jones', 'uid': 1003},
 {'fname': 'Big', 'lname': 'Jones', 'uid': 1004}]

07/01/2012
  {'address': '5412 N CLARK', 'date': '07/01/2012'}
  {'address': '4801 N BROADWAY', 'date': '07/01/2012'}
07/02/2012
  {'address': '5800 E 58TH', 'date': '07/02/2012'}
  {'address': '5645 N RAVENSWOOD', 'date': '07/02/2012'}
  {'address': '1060 W ADDISON', 'date': '07/02/2012'}
07/03/2012
  {'address': '2122 N CLARK', 'date': '07/03/2012'}
07/04/2012
  {'address': '5148 N CLARK', 'date': '07/04/2012'}
  {'address': '1039 W GRANVILLE', 'date': '07/04/2012'}


In [2]:
# 列表推导

# 获取大于0的元素，并且把元素*2
mylist = [5, 4, 7, 1, -1, 3, 0, -2, 5]
# [func(item) for item in items filter_condition(item)]
[n*2 for n in mylist if n > 0]

# 相当于上边的列表推导
mylist2 = map(lambda i: i*2, mylist)
list(filter(lambda i: i>0, mylist2))

# 把小于0的元素变成0，并且把元素*2
[n*2 if n >0 else 0 for n in mylist]
[n > 1 for n in mylist]

nums = [1, 2, 3, 4, 5]
sum(x * x for x in nums)
sum(nums)
min(nums)

# 字典推导
prices = {
    'ACME': 45.23,
    'AAPL': 612.78,
    'IBM': 205.55,
    'HPQ': 37.20,
    'FB': 10.75
}
# Make a dictionary of all prices over 200
{key: value for key, value in prices.items() if value > 200}
# Make a dictionary of tech stocks
tech_names = {'AAPL', 'IBM', 'HPQ', 'MSFT'}
{key: value for key, value in prices.items() if key in tech_names}

portfolio = [
    {'name':'GOOG', 'shares': 50},
    {'name':'YHOO', 'shares': 75},
    {'name':'AOL', 'shares': 20},
    {'name':'SCOX', 'shares': 65}
]
[s['shares'] for s in portfolio]
min(s['shares'] for s in portfolio)

# for生成器，相当于创建了一个iterator，iterator只能运行一次
gen = (s['shares'] for s in portfolio)
for s in gen:
    print(s)

[10, 8, 14, 2, 6, 10]

[10, 8, 14, 2, 6, 10]

[10, 8, 14, 2, 0, 6, 0, 0, 10]

[True, True, True, False, False, True, False, False, True]

55

15

1

{'AAPL': 612.78, 'IBM': 205.55}

{'AAPL': 612.78, 'HPQ': 37.2, 'IBM': 205.55}

[50, 75, 20, 65]

20

50
75
20
65


In [59]:
a = {"x": 1, "y":2}
b = {"y": 3, "z":4}
c = {"a": -1, "b": -2}
import collections
dict(collections.ChainMap(a,b,c))

l1 = list(zip(a.keys(), a.values()))
l2 = list(zip(b.keys(), b.values()))
l3 = list(zip(c.keys(), c.values()))
l1 + l2 + l3
dict(l1 + l2 + l3)

{'a': -1, 'b': -2, 'x': 1, 'y': 2, 'z': 4}

[('x', 1), ('y', 2), ('y', 3), ('z', 4), ('a', -1), ('b', -2)]

{'a': -1, 'b': -2, 'x': 1, 'y': 3, 'z': 4}