In [3]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的相关参数和变量。

In [4]:
batch_size = 8
dataset_size = 128
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y-input')
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1), trainable=True)
y = tf.nn.tanh(tf.matmul(x, w1))
# y = tf.matmul(x, w1)


#### 2. 设置自定义的损失函数。

In [5]:
# 定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测。
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

#### 3. 生成模拟数据集。

In [6]:
rdm = RandomState(1)
X = rdm.rand(dataset_size,2)
Y = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1, x2) in X]

#### 4. 训练模型。

In [7]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % dataset_size
        end = (i*batch_size) % dataset_size + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[-0.02263279]
 [ 2.19889712]] 

After 2000 training step(s), w1 is: 
[[ 0.5252797 ]
 [ 2.58517075]] 

After 3000 training step(s), w1 is: 
[[ 0.9152925 ]
 [ 2.81545806]] 

After 4000 training step(s), w1 is: 
[[ 1.14963746]
 [ 2.96198297]] 

Final w1 is: 
 [[ 1.32683945]
 [ 3.08070755]]


#### 5. 重新定义损失函数，使得预测多了的损失大，于是模型应该偏向少的方向预测。

In [8]:
loss_less = 1
loss_more = 10
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % dataset_size
        end = (i*batch_size) % dataset_size + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.48359871]] 

After 1000 training step(s), w1 is: 
[[ 0.05703859]
 [ 1.34017658]] 

After 2000 training step(s), w1 is: 
[[ 0.75677413]
 [ 1.16156507]] 

After 3000 training step(s), w1 is: 
[[ 1.07430112]
 [ 1.07888007]] 

After 4000 training step(s), w1 is: 
[[ 1.073686  ]
 [ 1.07864499]] 

Final w1 is: 
 [[ 1.07497787]
 [ 1.07789981]]


#### 6. 定义损失函数为MSE。

In [10]:
loss = tf.losses.mean_squared_error(y, y_)
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % dataset_size
        end = (i*batch_size) % dataset_size + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print(sess.run(w1), "\n")
    print("Final w1 is: \n", sess.run(w1))

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[-0.14825174]
 [ 2.08503127]] 

After 2000 training step(s), w1 is: 
[[ 0.24612428]
 [ 2.34614587]] 

After 3000 training step(s), w1 is: 
[[ 0.52946812]
 [ 2.46511173]] 

After 4000 training step(s), w1 is: 
[[ 0.75288743]
 [ 2.47879934]] 

Final w1 is: 
 [[ 0.9403336 ]
 [ 2.38410592]]
